### ISSUE TITLE
Basic meta field

### ISSUE THREAD

**Issue by janhenckens** [studioespresso/craft-seo-fields#6]
- [x] Title
- [x] Description
- [x] Sitename overwrite
- [x] Google results preview
- [x] Preview base on site defaults & default plugin settings
- [x] Add hide sitename option
